fix no default samesite
gorilla/sessions pull request #276
Opened 2024-04-21 17:07 UTC by bharat-rajani

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Go Version Update
- [ ] Dependency Update

## Description

This PR sets the SameSite cookie attribute to Lax in the Set-Cookie header. The SameSite=Lax value provides a reasonable balance between security and usability for websites.

Reference: 
https://owasp.org/www-community/SameSite

## Related Tickets & Documents

- Related Issue # https://github.com/gorilla/sessions/issues/256
- Closes # https://github.com/gorilla/sessions/issues/256

## Added/updated tests?

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Run verifications and test

- [X] `make verify` is passing
- [X] `make test` is passing

2024-04-22 09:24 UTC, jaitaiwan requested changes
From what I read of your linked comments, it seems like we should set the default to "None" for backwards compatible behaviour.

2024-04-22 09:24 UTC, jaitaiwan commented on .gitignore
> +.vscode
I'd like to see these in a separate pull request.

2024-04-22 12:24 UTC, bharat-rajani commented
@jaitaiwan https://github.com/gorilla/sessions/pull/276#pullrequestreview-2014240474
Some browsers are mandating additional Secure attribute when SameSite=None. 
( [chrome](https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure#:~:text=When%20the%20SameSite%3DNone%20attribute,provide%20protection%20against%20network%20attacks.), [firefox](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#none) ) 

I think it will be good to add Secure along with SameSite=None, let me know what you think!

2024-04-23 01:02 UTC, jaitaiwan commented
I think that's a good idea. We can release it under a major version tag so it doesn't break folk's installations either way.

2024-04-25 06:46 UTC, jaitaiwan commented
LGTM - Just waiting for scanning/tests to finish

2024-04-26 14:23 UTC, bharat-rajani commented
@jaitaiwan I believe vulncheck issues are unrelated and we can tackle them separately. 
Also, I ran linter locally and I don't see issues which are somehow reported in github workflow.
```
docker run -t --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.53.3 golangci-lint run -v
```

Can you help?

2024-05-01 06:49 UTC, apoorvajagtap commented
The linter is passing for me as well. I think this could be a false positive, I can't even find the existence of `max` reported in the error. 
I think we can ignore the lint errors, and as @bharat-rajani mentioned we can work through the vuln failures seperately. @jaitaiwan WDYT?

2024-05-26 03:41 UTC, jaitaiwan commented
We'll merge this once we've fixed #277 I think

2024-06-15 02:29 UTC, merged

2024-08-20 14:15 UTC, jaitaiwan commented
I think this might be missing from v1.4.0 can you check @bharat-rajani or @apoorvajagtap ?

2024-09-26 15:51 UTC, yhlee-tw commented
@jaitaiwan the new default `None`, like what @bharat-rajani has mentioned, breaks setup where they disable Secure (e.g. local HTTP server) . it's an easy fix but I thought it was planned for a major version bump (or at least, mentioned in release notes)